### ISSUE TITLE
Focus styles

### ISSUE THREAD

**Issue by oliverjam** [RunGT/FACCalculator#2]
It's important to make sure all your users know where they are while using your app. A big part of this is focus styles. Lots of users either cannot use a mouse or prefer to navigate with their keyboard for speed, so you need to ensure the currently focused element is highlights.

Buttons have a focus outline by default, but you have removed it with `outline: none`. It's ok to do this **as long as you replace the styles**. Right now when I hit tab I have no idea which button I'm on, which makes it pretty interesting to do calculations 😅

**Comment by RunGT** [comment]
Thanks, great to know. It is now fixed.
